import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Footer from "@/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-red-800">
          <ul className="flex justify-around text-red-500 p-4 text-2xl font-mono">
            <li> <Link href="/">Home</Link> </li>
            <li> <Link href="sobre">Sobre</Link> </li>
            <li> <Link href="posts">Posts</Link> </li>
            <li> <Link href="/produtos/categorias/eletronicos">Categorias</Link> </li>
            <li> <Link href="/perfil">Perfil</Link> </li>
          </ul>
  
        </nav>
        {children}

        <Footer/>
      </body>
    </html>
  );
}
